### ISSUE TITLE
Hacktoberfest 2022 - Help with documentation

### ISSUE THREAD

**Issue by CM-IV** [CM-IV/mef-api#21]
Hello contributors!

This is my first time as a Hacktoberfest maintainer, so cut me some slack. ;)

I'll have a CONTRIBUTING markdown file added to the master branch of the repository shortly.

This project is a REST API for making posts that I have made with the Gin Go web framework.  You can clone the project to have it running locally easily with docker-compose and air for live reloads.

I'd like some help fleshing out the remainder of the documentation and I will be accepting PRs/MRs to this end.

Leave a note under this issue if you're interested.

**Comment by oyamo** [comment]
Hi, I am interested, What help would you like?

**Comment by stevenanthonyrevo** [comment]
Welcome to hacktoberfest! 

@CM-IV I am interested in helping.

**Comment by CM-IV** [comment]
Hey @oyamo, thanks for reaching out!

The README in the master branch of the repo has a table of contents that shows there is unfinished documentation.

I am looking for some contributors to make pull requests with code examples from the repo and some explanations - not unlike what the rest of the README already shows.

**Comment by CM-IV** [comment]
Thanks @stevenanthonyrevo for the PR, I have looked over it and agree with what you've added.

The PR was merged to master.
